### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by modanova** [fac25/week7-away-days#146]
I don't understand how you're passing the set function as props
![image](https://user-images.githubusercontent.com/99407460/202249034-63a4d680-0bd3-4eb7-8530-4eb94a355cc7.png)
but the component takes the user
![image](https://user-images.githubusercontent.com/99407460/202249116-e2fedf98-66e5-4a68-b5ea-0d0d91be434c.png)

**Comment by KarwanM** [comment]
it is MAGIC!!!!

kidding, passing the "setUser" is extra, we forgot to delete it and "user" id the user account we get from AWS
